export const indianActors = [
  {
    name: "Shaharukh Khan",
    image: "./src/assets/srk.jpg",
    movies: [
      {
        id: 1,
        banner: "./src/assets/dev.jpg",
        title: "Devdas",
        stars: "Shah Rukh Khan, Madhuri Dixit",
        rating: "⭐⭐⭐⭐⭐ ⭐⭐☆☆ (7.5)",
        director: "Rakesh Roshan",
        year: 1997,
      },
      {
        id: 2,
        banner: "./src/assets/ram-lakhan.jpg",
        title: "Ram Lakhan",
        stars: "Anil Kapoor, Jackie Shroff, Madhuri Dixit",
        rating: "⭐⭐⭐⭐⭐ ⭐⭐☆☆ (7.5)",
        director: "Subhash Ghai",
        year: 1989,
      },
      {
        id: 3,
        banner: "./src/assets/mohabatten.jpg",
        title: "Mohabattein",
        stars: "Anil Kapoor, Jackie Shroff, Madhuri Dixit",
        rating: "⭐⭐⭐⭐⭐☆☆ (7.5)",
        director: "Subhash Ghai",
        year: 1989,
      },
      {
        id: 4,
        banner: "./src/assets/om.png",
        title: "Om Shanti Om",
        stars: "Shaharukh Khan, Dipika Padukon",
        rating: "⭐⭐⭐⭐⭐ ⭐⭐☆☆ (7.5)",
        director: "Subhash Ghai",
        year: 2000,
      },
      {
        id: 5,
        banner: "./src/assets/pathan.png",
        title: "Pathan",
        stars: "Shaharukh Khan",
        rating: "⭐⭐⭐⭐⭐ ⭐⭐☆☆ (7.5)",
        director: "Subhash Ghai",
        year: 1989,
      },
      {
        id: 6,
        banner: "./src/assets/jan.jpg",
        title: "Jab Tak Hai Jann",
        stars: "Shaharukh Khan, Katerina Kaif",
        rating: "⭐⭐⭐⭐⭐ ⭐⭐☆☆ (7.5)",
        director: "Subhash Ghai",
        year: 1989,
      },
      {
        id: 7,
        banner: "./src/assets/dilwale.jpg",
        title: "Dilwale Dulhaniya Le Jayenge",
        stars: "Shaharukh Khan",
        rating: "⭐⭐⭐⭐⭐ ⭐⭐☆☆ (7.5)",
        director: "Subhash Ghai",
        year: 1989,
      },
      {
        id: 8,
        banner: "./src/assets/rais.jpg",
        title: "RAEES",
        stars: "Shaharukh Khan",
        rating: "⭐⭐⭐⭐⭐ ⭐⭐☆☆ (7.5)",
        director: "Subhash Ghai",
        year: 1989,
      },
      {
        id: 9,
        banner: "./src/assets/vir.jpg",
        title: "Vir Zara",
        stars: "Shaharukh Khan",
        rating: "⭐⭐⭐⭐⭐ ⭐⭐☆☆ (7.5)",
        director: "Subhash Ghai",
        year: 1989,
      },
      {
        id: 10,
        banner: "./src/assets/bajigar.jpg",
        title: "Bajigar",
        stars: "Shaharukh Khan",
        rating: "⭐⭐⭐⭐⭐ ⭐⭐☆☆ (7.5)",
        director: "Subhash Ghai",
        year: 1989,
      },
    ],
  },
  {
    name: "Amitab Bachchan",
    image: "./src/assets/amitab.jpg",
    movies: [
      {
        id: 1,
        banner: "./src/assets/deewar.jpg",
        title: "Deewar",
        stars: "Amitab Bachchan",
        rating: "⭐⭐⭐⭐⭐ ⭐⭐☆☆ (7.5)",
        director: "Rakesh Roshan",
        year: 1997,
      },
      {
        id: 2,
        banner: "./src/assets/shole.jpg",
        title: "Sholey",
        stars: "Amitab Bachchan",
        rating: "⭐⭐⭐⭐⭐ ⭐⭐☆☆ (7.5)",
        director: "Rakesh Roshan",
        year: 1997,
      },
      {
        id: 3,
        banner: "./src/assets/sharabai.jpg",
        title: "Devdas",
        stars: "Shah Rukh Khan, Madhuri Dixit",
        rating: "⭐⭐⭐⭐⭐ ⭐⭐☆☆ (7.5)",
        director: "Rakesh Roshan",
        year: 1997,
      },
      {
        id: 4,
        banner: "./src/assets/sarkar.jpg",
        title: "Sarkar",
        stars: "Amitab Bachchan",
        rating: 7,
        director: "Rakesh Roshan",
        year: 1997,
      },
      {
        id: 5,
        banner: "./src/assets/agni.jpg",
        title: "Agnipath",
        stars: "Amirab Bachchan",
        rating: 7,
        director: "Rakesh Roshan",
        year: 1997,
      },
      {
        id: 6,
        banner: "./src/assets/janjir.jpg",
        title: "Janjir",
        stars: "Amitab Bachchan",
        rating: 7,
        director: "Rakesh Roshan",
        year: 1997,
      },
      {
        id: 7,
        banner: "./src/assets/silsila.jpg",
        title: "Silsila",
        stars: "Amitab Bacchan",
        rating: 7,
        director: "Rakesh Roshan",
        year: 1997,
      },
      {
        id: 8,
        banner: "./src/assets/shankti.jpg",
        title: "Shakti",
        rating: 7,
      },
      {
        id: 9,
        banner: "./src/assets/trishul.jpg",
        title: "Trishul",
        rating: 7,
      },
      {
        id: 10,
        banner: "./src/assets/don.jpg",
        title: "Don",
        stars: "Shah Rukh Khan, Madhuri Dixit",
        rating: 7,
        director: "Rakesh Roshan",
        year: 1997,
      },
    ],
  },
  {
    name: "Salman Khan",
    image: "./src/assets/salman.jpg",
    movies: [
      {
        id: 1,
        banner: "./src/assets/wanted.jpg",
        title: "Wanted",
        stars: "Salman Khan",
        rating: "⭐⭐⭐⭐☆ (4.0)",
        director: "Rakesh Roshan",
        year: 1997,
      },
      {
        id: 2,
        banner: "./src/assets/tigar.jpg",
        title: "Tigar",
        stars: "Salman Khan",
        rating: "⭐⭐⭐☆☆ (3.5)",
        director: "Rakesh Roshan",
        year: 1997,
      },
      {
        id: 3,
        banner: "./src/assets/sultan.jpg",
        title: "Sultan",
        stars: "Salman Khan",
        rating: "⭐⭐⭐⭐⭐☆☆ (5.5)",
        director: "Rakesh Roshan",
        year: 1997,
      },
      {
        id: 4,
        banner: "./src/assets/dabang.jpg",
        title: "Dabang",
        stars: "Salman Khan",
        rating: "⭐⭐⭐⭐⭐ ⭐⭐☆☆ (7.5)",
        director: "Rakesh Roshan",
        year: 1997,
      },
      {
        id: 5,
        banner: "./src/assets/kick.jpg",
        title: "Kick",
        stars: "Salman Khan",
        rating: "⭐⭐⭐⭐☆☆ (4.5)",
        director: "Rakesh Roshan",
        year: 1997,
      },
      {
        id: 6,
        banner: "./src/assets/part.jpg",
        title: "Part",
        stars: "Salman Khan",
        rating: "⭐⭐⭐⭐⭐⭐☆☆ (5.5)",
        director: "Rakesh Roshan",
        year: 1997,
      },
      {
        id: 7,
        banner: "./src/assets/tere.jpg",
        title: "Tere Naam",
        stars: "Salman Khan",
        rating: "⭐⭐⭐⭐⭐☆☆ (5.5)",
        director: "Rakesh Roshan",
        year: 1997,
      },
      {
        id: 8,
        banner: "./src/assets/humapke.jpg",
        title: "Hum Apke Hai Kon",
        stars: "Salman Khan",
        rating: "⭐⭐⭐⭐☆☆ (4.5)",
        director: "Rakesh Roshan",
        year: 1997,
      },
      {
        id: 9,
        banner: "./src/assets/dabang2.jpg",
        title: "Dabang 2",
        stars: "Salman Khan",
        rating: "⭐⭐⭐☆☆ (3.5)",
        director: "Rakesh Roshan",
        year: 1997,
      },
      {
        id: 10,
        banner: "./src/assets/body.jpg",
        title: "Bodygaurd",
        stars: "Salman Khan",
        rating: "⭐⭐⭐☆☆ (3.5)",
        director: "Rakesh Roshan",
        year: 1997,
      },
      {
        id: 11,
        banner: "./src/assets/bhaijan.jpg",
        title: "Bhaijaan",
        stars: "Salman Khan",
        rating: "⭐⭐⭐☆☆ (3.5)",
        director: "Rakesh Roshan",
        year: 1997,
      },
    ],
  },
  {
    name: "Ajay Devgan",
    image: "./src/assets/ajay.jpg",
    movies: [
      {
        id: 1,
        banner: "./src/assets/jigar.jpg",
        title: "Jigar",
        stars: "Ajay Devgan",
        rating: "⭐⭐⭐☆☆ (3.5)",
        director: "Rakesh Roshan",
        year: 1997,
      },
      {
        id: 2,
        banner: "./src/assets/dilwale.jpg",
        title: "Dilwale",
        stars: "Ajay Devgan",
        rating: "⭐⭐⭐⭐⭐☆☆ (5.5)",
        director: "Rakesh Roshan",
        year: 1997,
      },
      {
        id: 3,
        banner: "./src/assets/kacche.jpg",
        title: "Kacche Dhage",
        stars: "Ajay Devgan",
        rating: "⭐⭐⭐⭐⭐☆☆ (5.5)",
        director: "Rakesh Roshan",
        year: 1997,
      },
      {
        id: 4,
        banner: "./src/assets/jan.jpg",
        title: "Jan",
        stars: "Ajay Devgan",
        rating: "⭐⭐⭐⭐⭐☆☆ (5.5)",
        director: "Rakesh Roshan",
        year: 1997,
      },
      {
        id: 5,
        banner: "./src/assets/sangram.jpg",
        title: "Sangram",
        stars: "Ajay Devgan",
        rating: "⭐⭐⭐⭐⭐☆☆ (5.5)",
        director: "Rakesh Roshan",
        year: 1997,
      },
      {
        id: 6,
        banner: "./src/assets/diljale.jpg",
        title: "Diljale",
        stars: "Ajay Devgan",
        rating: "⭐⭐⭐⭐⭐☆☆ (5.5)",
        director: "Rakesh Roshan",
        year: 1997,
      },
      {
        id: 7,
        banner: "./src/assets/hakikat.jpg",
        title: "Hakikat",
        stars: "Ajay Devgan",
        rating: "⭐⭐⭐⭐⭐☆☆ (5.5)",
        director: "Rakesh Roshan",
        year: 1997,
      },
      {
        id: 8,
        banner: "./src/assets/singham.jpg",
        title: "Singham",
        stars: "Ajay Devgan",
        rating: "⭐⭐⭐⭐⭐☆☆ (5.5)",
        director: "Rakesh Roshan",
        year: 1997,
      },
      {
        id: 9,
        banner: "./src/assets/vijaypath.jpg",
        title: "Vijaypath",
        stars: "Ajay Devgan",
        rating: "⭐⭐⭐⭐⭐☆☆ (5.5)",
        director: "Rakesh Roshan",
        year: 1997,
      },
      {
        id: 10,
        banner: "./src/assets/jan.jpg",
        title: "Jan",
        stars: "Ajay Devgan",
        rating: "⭐⭐⭐⭐⭐☆☆ (5.5)",
        director: "Rakesh Roshan",
        year: 1997,
      },
      {
        id: 11,
        banner: "./src/assets/golmal.jpg",
        title: "Golmal",
        stars: "Ajay Devgan",
        rating: "⭐⭐⭐⭐⭐☆☆ (5.5)",
        director: "Rakesh Roshan",
        year: 1997,
      },
    ],
  },

  {
    name: "Axay Kumar",
    image: "./src/assets/axay.jpg",
    movies: [
      {
        id: 1,
        banner: "./src/assets/aan.jpg",
        title: "Aan",
        stars: "Axay Kumar",
        rating: "⭐⭐⭐⭐⭐☆☆ (5.5)",
        director: "Rakesh Roshan",
        year: 1997,
      },
      {
        id: 2,
        banner: "./src/assets/elan.jpg",
        title: "Elan",
        stars: "Axay Kumar",
        rating: "⭐⭐⭐⭐☆☆ (4.5)",
      },
      {
        id: 3,
        banner: "./src/assets/ab.jpg",
        title: "Ab Tumhare Hawale Watan",
        stars: "Axay Kumar",
        rating: "⭐⭐⭐⭐⭐☆☆ (5.5)",
        director: "Rakesh Roshan",
        year: 1997,
      },
      {
        id: 4,
        banner: "./src/assets/boss.jpg",
        title: "Boss",
        stars: "Axay Kumar",
        rating: "⭐⭐⭐⭐⭐☆☆ (5.5)",
        director: "Rakesh Roshan",
        year: 1997,
      },
      {
        id: 5,
        banner: "./src/assets/airlift.jpg",
        title: "Aairlift",
        stars: "Axay Kumar",
        rating: "⭐⭐⭐⭐⭐☆☆ (5.5)",
        director: "Rakesh Roshan",
        year: 1997,
      },
      {
        id: 6,
        banner: "./src/assets/babi.jpg",
        title: "Beby",
        stars: "Axay Kumar",
        rating: "⭐⭐⭐⭐⭐☆☆ (5.5)",
        director: "Rakesh Roshan",
        year: 1997,
      },
      {
        id: 7,
        banner: "./src/assets/gold.jpg",
        title: "Gold",
        stars: "Axay Kumar",
        rating: "⭐⭐⭐⭐⭐☆☆ (5.5)",
        director: "Rakesh Roshan",
        year: 1997,
      },
      {
        id: 8,
        banner: "./src/assets/rustam.jpg",
        title: "Roostam",
        stars: "Axay Kumar",
        rating: "⭐⭐⭐⭐⭐☆☆ (5.5)",
        director: "Rakesh Roshan",
        year: 1997,
      },
      {
        id: 9,
        banner: "./src/assets/omg.jpg",
        title: "Oh My God",
        stars: "Axay Kumar",
        rating: "⭐⭐⭐⭐⭐☆☆ (5.5)",
        director: "Rakesh Roshan",
        year: 1997,
      },
      {
        id: 10,
        banner: "./src/assets/kesari.jpg",
        title: "Kesari",
        stars: "Axay Kumar",
        rating: "⭐⭐⭐⭐⭐☆☆ (5.5)",
        director: "Rakesh Roshan",
        year: 1997,
      },
      {
        id: 11,
        banner: "./src/assets/saugandh.jpg",
        title: "Saugandh",
        stars: "Axay Kumar",
        rating: "⭐⭐⭐⭐⭐☆☆ (5.5)",
        director: "Rakesh Roshan",
        year: 1997,
      },
    ],
  },
  {
    name: "Sanjay Datt",
    image: "./src/assets/sanjay.jpg",
    movies: [
      {
        id: 1,
        banner: "./src/assets/sajan.jpg",
        title: "Sajan",
        stars: "Sanjay Dutt",
        rating: "⭐⭐⭐⭐⭐☆☆ (5.5)",
        director: "Rakesh Roshan",
        year: 1997,
      },
      {
        id: 2,
        banner: "./src/assets/sanam.jpg",
        title: "Sanam",
        stars: "Sanam",
        rating: "⭐⭐⭐⭐⭐☆☆ (5.5)",
        director: "Rakesh Roshan",
        year: 1997,
      },
      {
        id: 3,
        banner: "./src/assets/sahiba.jpg",
        title: "Sahiba",
        stars: "Sanjay Dutt",
        rating: "⭐⭐⭐⭐⭐☆☆ (5.5)",
        director: "Rakesh Roshan",
        year: 1997,
      },
      {
        id: 4,
        banner: "./src/assets/naam.jpg",
        title: "Naam",
        stars: "Sanjay Dutt",
        rating: "⭐⭐⭐⭐⭐☆☆ (5.5)",
        director: "Rakesh Roshan",
        year: 1997,
      },
      {
        id: 5,
        banner: "./src/assets/kuru.jpg",
        title: "Kuruxetra",
        stars: "Sanjay Dutt",
        rating: "⭐⭐⭐⭐⭐☆☆ (5.5)",
        director: "Rakesh Roshan",
        year: 1997,
      },
      {
        id: 6,
        banner: "./src/assets/saugandh.jpg",
        title: "Saugandh",
        stars: "Sanjay Dutt",
        rating: "⭐⭐⭐⭐⭐☆☆ (5.5)",
        director: "Rakesh Roshan",
        year: 1997,
      },
      {
        id: 7,
        banner: "./src/assets/jaharile.jpg",
        title: "Jaharile",
        stars: "Sanjay Dutt",
        rating: "⭐⭐⭐⭐⭐☆☆ (5.5)",
        director: "Rakesh Roshan",
        year: 1997,
      },
      {
        id: 8,
        banner: "./src/assets/dushman.jpg",
        title: "Dushman",
        stars: "Sanjay Dutt",
        rating: "⭐⭐⭐⭐⭐☆☆ (5.5)",
        director: "Rakesh Roshan",
        year: 1997,
      },
      {
        id: 9,
        banner: "./src/assets/vasatv.jpg",
        title: "Vastav",
        stars: "Sanjay Dutt",
        rating: "⭐⭐⭐⭐⭐☆☆ (5.5)",
        director: "Rakesh Roshan",
        year: 1997,
      },
      {
        id: 10,
        banner: "./src/assets/panipat.jpg",
        title: "Panipat",
        stars: "Sanjay Dutt",
        rating: "⭐⭐⭐⭐⭐☆☆ (5.5)",
        director: "Rakesh Roshan",
        year: 1997,
      },
    ],
  },
  {
    name: "Rushi Kapoor",
    image: "./src/assets/rushi.jpg",
    movies: [
      {
        id: 1,
        banner: "./src/assets/bade_dilwala.jpg",
        title: "Bade Dilwala",
        stars: "Rushi Kapoor",
        rating: "⭐⭐⭐⭐⭐☆☆ (5.5)",
        director: "Rakesh Roshan",
        year: 1997,
      },
      {
        id: 2,
        banner: "./src/assets/dil_ki_lagi.jpg",
        title: "Dil Ki Lagi",
        stars: "Sanjay Dutt",
        rating: "⭐⭐⭐⭐⭐☆☆ (5.5)",
        director: "Rakesh Roshan",
        year: 1997,
      },
      {
        id: 3,
        banner: "./src/assets/anmol.jpg",
        title: "Anmol",
        stars: "Rushi Kapoor",
        rating: "⭐⭐⭐⭐⭐☆☆ (5.5)",
        director: "Rakesh Roshan",
        year: 1997,
      },
      {
        id: 4,
        banner: "./src/assets/karj.jpg",
        title: "Karj",
        stars: "Rushi Kapoor",
        rating: "⭐⭐⭐⭐⭐☆☆ (5.5)",
        director: "Rakesh Roshan",
        year: 1997,
      },
      {
        id: 5,
        banner: "./src/assets/hina.jpg",
        title: "Hina",
        stars: "Rushi Kapoor",
        rating: "⭐⭐⭐⭐⭐☆☆ (5.5)",
        director: "Rakesh Roshan",
        year: 1997,
      },
      {
        id: 6,
        banner: "./src/assets/araju.jpg",
        title: "Araju",
        stars: "Rushi Kapoor",
        rating: "⭐⭐⭐⭐⭐☆☆ (5.5)",
        director: "Rakesh Roshan",
        year: 1997,
      },
      {
        id: 7,
        banner: "./src/assets/radha.jpg",
        title: "Radha",
        stars: "Rushi Kapoor",
        rating: "⭐⭐⭐⭐⭐☆☆ (5.5)",
        director: "Rakesh Roshan",
        year: 1997,
      },
      {
        id: 8,
        banner: "./src/assets/yarana.jpg",
        title: "Yarana",
        stars: "Rushi Kapoor",
        rating: "⭐⭐⭐⭐⭐☆☆ (5.5)",
        director: "Rakesh Roshan",
        year: 1997,
      },
      {
        id: 9,
        banner: "./src/assets/chandani.jpg",
        title: "Chandani",
        stars: "Rushi Kapoor",
        rating: "⭐⭐⭐⭐⭐☆☆ (5.5)",
        director: "Rakesh Roshan",
        year: 1997,
      },
      {
        id: 10,
        banner: "./src/assets/kasak.jpg",
        title: "Kasak",
        stars: "Sanjay Dutt",
        rating: "⭐⭐⭐⭐⭐☆☆ (5.5)",
        director: "Rakesh Roshan",
        year: 1997,
      },
    ],
  },
  {
    name: "Ranvir Kapoor",
    image: "./src/assets/ranvir.jpg",
    movies: [
      {
        id: 1,
        banner: "./src/assets/aedil.jpg",
        title: "Ae Dil Hai Mushkil",
        stars: "Ranvir Kapoor",
        rating: "⭐⭐⭐⭐⭐☆☆ (5.5)",
        director: "Rakesh Roshan",
        year: 1997,
      },
      {
        id: 2,
        banner: "./src/assets/animal.jpg",
        title: "Animal",
        stars: "Ranvir Kapoor",
        rating: "⭐⭐⭐⭐⭐☆☆ (5.5)",
        director: "Rakesh Roshan",
        year: 1997,
      },
      {
        id: 3,
        banner: "./src/assets/rockstar.jpg",
        title: "Rockstar",
        stars: "Ranvir Kapoor",
        rating: "⭐⭐⭐⭐⭐☆☆ (5.5)",
        director: "Rakesh Roshan",
        year: 1997,
      },
      {
        id: 4,
        banner: "./src/assets/jagga.jpg",
        title: "Jagga Jasus",
        stars: "Ranvir Kapoor",
        rating: "⭐⭐⭐⭐⭐☆☆ (5.5)",
        director: "Rakesh Roshan",
        year: 1997,
      },
      {
        id: 5,
        banner: "./src/assets/aedil.jpg",
        title: "Dil Dhadakane Do",
        stars: "Ranvir Kapoor",
        rating: "⭐⭐⭐⭐⭐☆☆ (5.5)",
        director: "Rakesh Roshan",
        year: 1997,
      },
      {
        id: 6,
        banner: "./src/assets/aedil.jpg",
        title: "Ae Dil Hai Mushkil",
        stars: "Ranvir Kapoor",
        rating: "⭐⭐⭐⭐⭐☆☆ (5.5)",
        director: "Rakesh Roshan",
        year: 1997,
      },
      {
        id: 7,
        banner: "./src/assets/barfi.jpg",
        title: "Barfi",
        stars: "Ranvir Kapoor",
        rating: "⭐⭐⭐⭐⭐☆☆ (5.5)",
        director: "Rakesh Roshan",
        year: 1997,
      },
      {
        id: 8,
        banner: "./src/assets/sawariya.jpg",
        title: "Sawariya",
        stars: "Ranvir Kapoor",
        rating: "⭐⭐⭐⭐⭐☆☆ (5.5)",
        director: "Rakesh Roshan",
        year: 1997,
      },
      {
        id: 9,
        banner: "./src/assets/bombay_wallet.jpg",
        title: "Bombay Wallet",
        stars: "Ranvir Kapoor",
        rating: "⭐⭐⭐⭐⭐☆☆ (5.5)",
        director: "Rakesh Roshan",
        year: 1997,
      },
      {
        id: 10,
        banner: "./src/assets/barfi.jpg",
        title: "Barfi",
        stars: "Ranvir Kapoor",
        rating: "⭐⭐⭐⭐⭐☆☆ (5.5)",
        director: "Rakesh Roshan",
        year: 1997,
      },
    ],
  },
  {
    name: "Amir Khan",
    image: "./src/assets/amir.jpg",
    movies: ["Dhoom 3", "Ghajini"],
    awards: ["Filmfare Award", "Zee Cine Award"],
    birthdate: "1976-09-05",
    deathdate: "",
    birthplace: "Hyderabad, Telangana, India",
    deathplace: "",
    bio: "Vivek Oberoi is an Indian actor known for his roles in Bollywood action and romantic films.",
  },
  {
    name: "Govinda Ahuja",
    image: "./src/assets/govinda.jpg",
    movies: ["Dhoom 3", "Ghajini"],
    awards: ["Filmfare Award", "Zee Cine Award"],
    birthdate: "1976-09-05",
    deathdate: "",
    birthplace: "Hyderabad, Telangana, India",
    deathplace: "",
    bio: "Vivek Oberoi is an Indian actor known for his roles in Bollywood action and romantic films.",
  },
];

export const topTenMovies = [
  {
    id: 2,
    title: "Ghatak",
    banner: "./src/assets/koyala.jpg",
    year: 1996,
    rating: 7.4,
    awards: "Filmfare Award",
    director: "Rajkumar Santoshi",
    stars: "Sunny Deol, Raveena Tandon, Amrish Puri",
    story:
      "A man fights a tyrannical gangster to protect a small village from oppression.",
  },
  {
    id: 3,
    title: "Koyla",
    year: 1997,
    rating: 7.3,
    awards: "Filmfare Award",
    director: "Rakesh Roshan",
    stars: "Shah Rukh Khan, Madhuri Dixit, Amrish Puri",
    story:
      "A mute servant avenges the wrongs committed by a ruthless landlord.",
  },
  {
    id: 4,
    title: "Koyla",
    year: 1997,
    rating: 7.3,
    awards: "Filmfare Award",
    director: "Rakesh Roshan",
    stars: "Shah Rukh Khan, Madhuri Dixit, Amrish Puri",
    story:
      "A mute servant avenges the wrongs committed by a ruthless landlord.",
  },
  {
    id: 5,
    title: "Koyla",
    year: 1997,
    rating: 7.3,
    awards: "Filmfare Award",
    director: "Rakesh Roshan",
    stars: "Shah Rukh Khan, Madhuri Dixit, Amrish Puri",
    story:
      "A mute servant avenges the wrongs committed by a ruthless landlord.",
  },
  {
    id: 6,
    title: "Koyla",
    year: 1997,
    rating: 7.3,
    awards: "Filmfare Award",
    director: "Rakesh Roshan",
    stars: "Shah Rukh Khan, Madhuri Dixit, Amrish Puri",
    story:
      "A mute servant avenges the wrongs committed by a ruthless landlord.",
  },
  {
    id: 7,
    title: "Koyla",
    year: 1997,
    rating: 7.3,
    awards: "Filmfare Award",
    director: "Rakesh Roshan",
    stars: "Shah Rukh Khan, Madhuri Dixit, Amrish Puri",
    story:
      "A mute servant avenges the wrongs committed by a ruthless landlord.",
  },
  {
    id: 8,
    title: "Koyla",
    year: 1997,
    rating: 7.3,
    awards: "Filmfare Award",
    director: "Rakesh Roshan",
    stars: "Shah Rukh Khan, Madhuri Dixit, Amrish Puri",
    story:
      "A mute servant avenges the wrongs committed by a ruthless landlord.",
  },
  {
    id: 9,
    title: "Koyla",
    year: 1997,
    rating: 7.3,
    awards: "Filmfare Award",
    director: "Rakesh Roshan",
    stars: "Shah Rukh Khan, Madhuri Dixit, Amrish Puri",
    story:
      "A mute servant avenges the wrongs committed by a ruthless landlord.",
  },
  {
    id: 10,
    title: "Koyla",
    year: 1997,
    rating: 7.3,
    awards: "Filmfare Award",
    director: "Rakesh Roshan",
    stars: "Shah Rukh Khan, Madhuri Dixit, Amrish Puri",
    story:
      "A mute servant avenges the wrongs committed by a ruthless landlord.",
  },
  {
    id: 1,
    title: "Koyla",
    year: 1997,
    rating: 7.3,
    awards: "Filmfare Award",
    director: "Rakesh Roshan",
    stars: "Shah Rukh Khan, Madhuri Dixit, Amrish Puri",
    story:
      "A mute servant avenges the wrongs committed by a ruthless landlord.",
  },
  {
    id: 2,
    title: "Koyla",
    year: 1997,
    rating: 7.3,
    awards: "Filmfare Award",
    director: "Rakesh Roshan",
    stars: "Shah Rukh Khan, Madhuri Dixit, Amrish Puri",
    story:
      "A mute servant avenges the wrongs committed by a ruthless landlord.",
  },
];
